### ISSUE TITLE
Update installation guide in README.md to use python venv

### ISSUE THREAD

**Issue by Temzasse** [Temzasse/ntu-crysis#1]
Check out the previous README.d file from version history and copy the venv related stuff to the new README

**Comment by Temzasse** [comment]
The server instructions should not guide the developer to install all dependencies globally. Use Virtualenv: http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by Temzasse** [comment]
Instructions should include Windows specific steps too. The complete instructions can be basically copy&pasted from my initial server commit: https://github.com/Temzasse/ntu-crysis/commit/e5cad86291e136f640da4d51112d576403bc0742#diff-7d62b4cde47a08800e3b7212ca2dd397

**Comment by Temzasse** [comment]
Also dependencies should be listed in requirements.txt file so they can be easily installed with `pip install -r requirements.txt`

**Comment by Temzasse** [comment]
Currently installed deps can be added to `requirements.txt` file like this: `pip freeze > requirements.txt`

**Comment by NTUFQ** [comment]
Thanks! I have changed README.
