### ISSUE TITLE
Create ER-diagram to specify models

### ISSUE THREAD

**Issue by Temzasse** [Temzasse/ntu-crysis#7]
ER-diagram would help a lot with the design of the models.

Check `models.py` for some notes about the current models implementation.

**Comment by NTUFQ** [comment]
![alt tag](https://s15.postimg.org/9z1ed6rqj/Screen_Shot_2016_10_03_at_11_21_05_PM.png)

**Comment by Temzasse** [comment]
@NTUFQ did you take a look at my notes (marked with # NOTE) in the `models.py` file? I think we need to refine this ER-diagram a bit. I can create my view of the diagram to start up the discussion.

**Comment by Temzasse** [comment]
Here link to the notes: https://github.com/Temzasse/ntu-crysis/blob/master/server/crysis/cms/models.py#L16

**Comment by Temzasse** [comment]
@NTUFQ 
Here is my version of the ER-diagram: https://www.lucidchart.com/invitations/accept/01f09fd7-63af-4e93-b850-906d45a690e6

Comparison to prev diagram:
- Response units are attached to Incidents not to Crisis
  - In the end response units are the ones that handle the incident
- Response unit should have a speciality that maps to some Incident type (land / sea / air etc.)
- Response unit type can simply be one of "trainer" / "police" / "military"
  - We might want to create classes for these, not sure tho
- Crisis doesn't need lat/long fields
- Crisis should have status or state field that can be for example: inactive / active / resolved
- Crisis level is basically just the number of active incidents (not handled yet by response unit)
  - When the level surpasses the Crisis threshold => status/state becomes active!
- Shelter is leaved out from diagram atm because it's a separate thing from Crisis
